<a href="https://colab.research.google.com/github/Alessandrags/pandas-entrada-e-saida-de-dados/blob/main/Pandas_i_O.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Fazendo leitura de arquivos CSV

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'

In [ ]:
dados_mercado = pd.read_csv(url)

In [ ]:
dados_mercado.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
url_2 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv'

In [ ]:
dados_ponto_virgula = pd.read_csv(url_2)

In [ ]:
dados_ponto_virgula.head()

  Id;Year_Birth;Education;Marital_Status;Income;Kidhome;Teenhome;Dt_Customer;Recency;MntWines;MntFruits;MntMeatProducts;MntFishProducts;MntSweetProducts;MntGoldProds;NumDealsPurchases;NumWebPurchases;NumCatalogPurchases;NumStorePurchases;NumWebVisitsMonth;Response;Complain
0  1826;1970;Graduation;Divorced;84835;0;0;6/16/2...
1  1;1961;Graduation;Single;57091;0;0;6/15/2014;0...
2  10476;1958;Graduation;Married;67267;0;1;5/13/2...
3  1386;1967;Graduation;Together;32474;1;1;11/5/2...
4  5371;1989;Graduation;Single;21474;1;0;8/4/2014...

In [ ]:
dados_ponto_virgula = pd.read_csv(url_2, sep = ';')

In [ ]:
dados_ponto_virgula.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
#Parâmetro nrows = auxilia na utilização da memória apresentando apenas as linhas determinadas neste parametro.

dados_primeiras_linhas = pd.read_csv(url,nrows=5)

In [ ]:
dados_primeiras_linhas

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
#Parametro usecols = também auxilia na utilização da memoria apresentando apenas as colunas determinadas através de nomes ou index

dados_selecao = pd.read_csv(url, usecols=['Id', 'Year_Birth', 'Income'])

In [ ]:
dados_selecao

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [ ]:
dados_selecao = pd.read_csv(url, usecols=[0,1,4])

In [ ]:
dados_selecao.head()

      Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

In [ ]:
dados_selecao.to_csv('clientes_mercado.csv')

In [ ]:
clientes_mercado = pd.read_csv('/content/clientes_mercado.csv')

In [ ]:
clientes_mercado.head()

   Unnamed: 0     Id  Year_Birth   Income
0           0   1826        1970  84835.0
1           1      1        1961  57091.0
2           2  10476        1958  67267.0
3           3   1386        1967  32474.0
4           4   5371        1989  21474.0

In [ ]:
dados_selecao.to_csv('dados_mercado.csv', index=False)

In [ ]:
pd.read_csv('/content/dados_mercado.csv')

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

## Para saber mais : erro de enconding - Como resolver?

In [ ]:
import pandas as pd
df = pd.read_csv('/content/dados.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/dados.csv'

In [ ]:
#Biblioteca utiliza para auxiliar na identificação do enconding.

import chardet

In [ ]:
with open('/content/dados_mercado.csv', 'rb') as file:
    print(chardet.detect(file.read()))

In [ ]:
df = pd.read_csv('/content/dados_mercado.csv', encoding='ascii')

In [ ]:
df.head()

## Desafio: lendo dados com vários parâmetros

Chegou a hora de você testar os conhecimentos desenvolvidos durante a aula. Temos um arquivo no formato CSV, que foi obtido na página Informações de Saúde (TABNET) - DATASUS. Este arquivo contém os gastos hospitalares públicos de cada uma das Unidades da Federação brasileira no período de janeiro de 2008 a março de 2021.

Seu desafio aqui será fazer a leitura desse arquivo utilizando a função read_csv da biblioteca Pandas. Alguns parâmetros devem ser adicionados para que a leitura seja feita corretamente. Então, seguem algumas dicas:

1. Verifique se o arquivo CSV está separado por vírgula ou ponto e vírgula.

**Resposta**: Com ponto e vírgula

2. A codificação do arquivo é ISO-8859-1.

**Resposta**: Sim

In [ ]:
import pandas as pd

dados_sus = pd.read_csv('/content/dados_sus.csv')

In [ ]:
import chardet

In [ ]:
with open('/content/dados_sus.csv', 'rb') as file:
    print(chardet.detect(file.read()))

3. As três primeiras linhas linhas do arquivo podem ser desconsideradas, pois o cabeçalho só começa na quarta linha.

4. As 9 últimas linhas também podem ser desconsideradas, pois são apenas informações sobre onde os dados foram obtidos.

5. Para deletar as últimas linhas é necessário adicionar o parâmetro engine='python'.

In [ ]:
dados_sus = pd.read_csv('/content/dados_sus.csv', \
            encoding='ISO-8859-1', sep =";", skiprows=3, skipfooter=9, engine='python')

In [ ]:
dados_sus.head()

#2. Lendo arquivos Excel

In [ ]:
import pandas as pd

In [ ]:
#no GitHub não é possível ler os dados brutos, ele então baixo o arquivo excel, fazendo a leitura desta forma após o nome da extensão é inserido: "?raw=True"

url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

In [ ]:
dados_co2 = pd.read_excel(url)

In [ ]:
dados_co2.head(5)

In [ ]:
#Classe para saber se na planilha há outras abas(páginas)

pd.ExcelFile(url).sheet_names

In [ ]:
#fazendo a leitura da segunda aba da planilha

percapita = pd.read_excel(url, sheet_name='emissoes_percapita')

In [ ]:
percapita.head(5)

In [ ]:
#fazendo a leitura da última aba da planilha

fontes = pd.read_excel(url, sheet_name='fontes')

In [ ]:
fontes.head(5)

In [ ]:
# Trazendo somente as colunas de interesse com o parâmetro: usecols.

intervalo = pd.read_excel(url, sheet_name='emissoes_C02', usecols='A:D')

In [ ]:
intervalo.head(5)

In [ ]:
# Trazendo somente as linhas de interesse com o parâmetro: nrows

intervalo_2 = pd.read_excel(url, sheet_name='emissoes_C02', usecols='A:D',nrows=10)

In [ ]:
intervalo_2

In [ ]:
percapita.to_excel('percapita.xlsx', index=False)

In [ ]:
pd.read_excel('/content/percapita.xlsx')

In [ ]:
#link da planilha no GoogleSheets

https://docs.google.com/spreadsheets/d/1DsBeRkaAEZMhcpBfaVUjCzheSK0QmWXETY997HsTfnI/edit?usp=sharing

In [ ]:
#separando o id da planilha

sheet_id = '1DsBeRkaAEZMhcpBfaVUjCzheSK0QmWXETY997HsTfnI'

In [ ]:
#No link do GoogleSheets, apagar tudo após o 'd/' e inserir o f-string para chamar a variável com o Id da planilha.
#Após isso será incluido um novo parâmetro gviz/tq para ter acesso a planilha é necessário acessar a API de visualização de dados do Google, criando a comunicação entre
#Google Colab e o Google Planilhas. Após isso será adicionado: '??tqx=out:csv&sheet', para que desta forma seja retornado os arquivos no formato 'csv'.

url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
dados_co2_sheets = pd.read_csv(url)

In [ ]:
dados_co2_sheets.head(5)

In [ ]:
#Selecionado outra aba da planilha.

sheet_id = '1DsBeRkaAEZMhcpBfaVUjCzheSK0QmWXETY997HsTfnI'
sheet_name = 'emissoes_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
percapita_sheets = pd.read_csv(url_percapita)

In [ ]:
percapita_sheets.head(5)

In [ ]:
#Selecionado a última aba da planilha.

sheet_id = '1DsBeRkaAEZMhcpBfaVUjCzheSK0QmWXETY997HsTfnI'
sheet_name = 'fontes'
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
fontes_sheets = pd.read_csv(url_fontes)

In [ ]:
fontes_sheets.head()

## Desafio: lendo dados de outro link

Chegou a hora de você testar os conhecimentos desenvolvidos durante a aula. Nós temos um [link do Google Planilhas](https://docs.google.com/spreadsheets/d/1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw/edit?gid=1214654498#gid=1214654498) que contém dados importantes sobre as emissões de gás carbônico pelo mundo. O conjunto de dados foi obtido no [Kaggle](https://www.kaggle.com/datasets/koustavghosh149/co2-emission-around-the-world) e consiste em emissões de CO2 per capita de todos os países do mundo de 1990 a 2019.

Neste desafio, a sua função é efetuar a leitura desse link do Google Planilhas e depois salvar o DataFrame obtido no formato CSV. Pronto(a) para começar?

In [ ]:
https://docs.google.com/spreadsheets/d/1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw/edit?gid=1214654498#gid=1214654498

In [ ]:
sheet_id_2 = '1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'

In [ ]:
url_3 = f'https://docs.google.com/spreadsheets/d/{sheet_id_2}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
emissoes_co = pd.read_csv(url_3)

In [ ]:
emissoes_co.head()

In [ ]:
emissoes_co.to_csv('emissoes_co.csv', index=False)

# Manipulando arquivos JSON

In [ ]:
import pandas as pd

In [ ]:
dados_pacientes = pd.read_json('/content/pacientes.json')

In [ ]:
dados_pacientes.head()

In [ ]:
#Arquivo Json aninhado

dados_pacientes_2 = pd.read_json('/content/pacientes_2.json')

In [ ]:
dados_pacientes_2

In [ ]:
#Função para normalizar o arquivo json aninhado.

df_normalizado = pd.json_normalize(dados_pacientes_2['Pacientes'])

In [ ]:
df_normalizado

In [ ]:
df_normalizado.to_json('historico_pacientes_normalizados.json')

In [ ]:
pd.read_json('/content/historico_pacientes_normalizados.json')

# Para saber mais: obtendo arquivos JSON de APIs

Para obter dados no formato JSON podemos utilizar uma API (Application Programming Interface). Ela é uma interface de programação de aplicação que permite a comunicação entre diferentes programas ou sistemas.

Atenção: Caso queira aprofundar no assunto, temos um Alura + explicando o que é uma API.

Existem vários formatos que podem ser usados em APIs e um dos mais comuns é o JSON (JavaScript Object Notation). O JSON é um formato leve de troca de informações entre sistemas que utiliza uma notação baseada em objetos do JavaScript.

Nós temos a seguinte situação-problema: “Uma empresa de tecnologia está em fase de expansão e deseja otimizar sua base de contatos e a forma como gerencia suas interações com os clientes e parceiros. A equipe de vendas e atendimento ao cliente está enfrentando dificuldades para acompanhar todos os contatos, entender as necessidades dos diferentes perfis de clientes, e personalizar o atendimento de forma eficiente. Para solucionar isso, a empresa precisa de uma maneira organizada e automatizada para coletar, gerenciar e segmentar informações de seus clientes e parceiros, como nome, e-mail, endereço, telefone e empresa em que trabalham.”

Nesta situação, podemos acessar a API [JSONPlaceholder](https://jsonplaceholder.typicode.com/users) para coletar os dados dos contatos, que incluem nome, e-mail, endereço, telefone, entre outros. Com esses dados, a equipe pode melhorar suas operações e a comunicação com os clientes.

Uma maneira comum de acessar APIs é por meio da biblioteca [requests](https://pypi.org/project/requests/). Para isso, também é necessário importar o módulo json:

In [ ]:
import requests
import json

Os dados da JSONPlaceholder serão obtidos com a função request.get('url'). Dentro dela nós passamos o endereço da API:

In [ ]:
dados_usuarios = requests.get('https://jsonplaceholder.typicode.com/users')

Conseguimos recuperar os resultados usando a função json.loads(). Para isso, é necessário passar a variável dados_usuarios, criada anteriormente com o atributo text que retorna o conteúdo da resposta.

In [ ]:
resultado = json.loads(dados_usuarios.text)

Em seguida, podemos visualizar o DataFrame.

In [ ]:
pd.DataFrame(resultado)

Agora sabemos como utilizar a biblioteca requests e o módulo JSON para obter dados de APIs!

## Desafio: normalizando o JSON obtindo na API

Chegou a hora de testar os conhecimentos desenvolvidos durante a aula.

O DataFrame mostrado abaixo foi gerado após a obtenção de dados da API [JSONPlaceholder](https://jsonplaceholder.typicode.com/users):

Este DataFrame possui 8 colunas: id, name (nome), username (nome de usuário), email , address (endereço), phone(telefone), website e company (empresa). Note que as colunas address e company contém informações aninhadas, ou seja, os dados dessas colunas estão organizados em subcampos. Por exemplo, na coluna address, você encontrará subcampos como street (rua), suite (complemento), city (cidade) e zipcode (CEP). Já na coluna company, os subcampos incluem name (nome da empresa), catchPhrase (slogan) e bs (área de atuação). Isso significa que, para acessar essas informações, é necessário realizar o processo de normalização.

O desafio agora é normalizar esse DataFrame, expandindo as colunas address e company em suas respectivas subcolunas para facilitar a visualização e a análise dos dados.

Se você tiver dúvidas sobre como resolver, consulte a opinião da pessoa instrutora!

In [ ]:
import pandas as pd
import requests
import json

In [ ]:
df_companhia = requests.get('https://jsonplaceholder.typicode.com/users')

In [ ]:
resultado_companhia = json.loads(df_companhia.text)

In [ ]:
#Função para normalizar o arquivo json aninhado.

resultado_companhia_normalizado = pd.json_normalize(resultado_companhia,sep='_')

In [ ]:
resultado_companhia_normalizado.head()

# Lendo dados em HTML e XML

In [ ]:
import pandas as pd

In [ ]:
dados_html = pd.read_html('/content/filmes_wikipedia.html')

In [ ]:
dados_html

In [ ]:
type(dados_html)

In [ ]:
len(dados_html)

In [ ]:
top_filmes = dados_html[1]

In [ ]:
top_filmes

In [ ]:
top_filmes.to_html('top_filmes.html')

In [ ]:
top_filmes.to_csv('top_filmes_1998.csv', index=False)

In [ ]:
pd.read_csv('/content/top_filmes_1998.csv')

In [ ]:
import pandas as pd

In [ ]:
dados_imdb = pd.read_xml('/content/imdb_top_1000.xml')

In [ ]:
dados_imdb.head(3)

In [ ]:
dados_imdb.to_xml('filmes_imdb.xml')

## Desafio: lendo uma tabela de uma página web

Chegou a hora de testar os conhecimentos desenvolvidos durante a aula.

Vanessa é uma cientista de dados que está realizando algumas análises com dados ambientais. Ela está desenvolvendo um projeto para avaliar o impacto ambiental das atividades humanas em diferentes países do mundo, mas para isso precisa das estimativas populacionais desses países. Ao pesquisar na internet, encontrou uma tabela de estimativas populacionais em um artigo da página [Wikipédia](https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o).

Assim como Vanessa, seu desafio é obter um DataFrame da tabela que contém as informações do número de habitantes de cada país.

In [ ]:
import pandas as pd
dados_html = pd.read_html('/content/Lista de países por população – Wikipédia, a enciclopédia livre.html')
dados_html

In [ ]:
paises = dados_html[0]
paises

In [ ]:
#outra forma de visualizar sem precisar fazer o upload do arquivo html

pd.read_html('https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o')[0]

# Trabalhando com banco de dados

In [ ]:
import sqlalchemy

In [ ]:
from sqlalchemy import create_engine, MetaData, Table, inspect

In [ ]:
engine = create_engine('sqlite:///:memory:')

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/refs/heads/main/clientes_banco.csv'

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_csv(url)

In [ ]:
dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [ ]:
dados.to_sql('clientes', engine, index=False)

438463

In [ ]:
inspector = inspect(engine)

In [ ]:
print(inspector.get_table_names())

['clientes']

In [ ]:
#criando uma variável para armanezar a consulta SQL

query = 'SELECT * FROM clientes WHERE Categoria_de_renda = "Empregado"'

In [ ]:
#Executando a consulta e armazenando e uma nova variável

empregados = pd.read_sql(query, engine)

In [ ]:
empregados

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
empregados.to_sql('empregados', con=engine, index=False)

226059

In [ ]:
#lendo uma tabela inteira

pd.read_sql_table('empregados', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
#lendo uma tabela e utilizando parametros para selecionar apenas algumas colunas especificas.

pd.read_sql_table('empregados', engine, columns=['ID_Cliente', 'Grau_escolaridade', 'Rendimento_anual'])

        ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

In [ ]:
from sqlalchemy import text

In [ ]:
query = 'SELECT * FROM clientes'

In [ ]:
pd.read_sql(text(query), engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
query = 'DELETE FROM clientes WHERE ID_Cliente = 5008804'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

In [ ]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
2,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
query ='UPDATE clientes SET Grau_escolaridade = "Ensino superior" WHERE ID_Cliente = 5008808'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

In [ ]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
2,5008808,52,Ensino superior,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

## Desafio:  manipulando um banco de dados

Chegou a hora de testar os conhecimentos desenvolvidos durante a aula.

Você é responsável por criar um banco de dados local de clientes para uma instituição financeira. Temos o [arquivo CSV](https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv) com os dados de clientes.

Sua missão é:

1. Criar o banco de dados local com a biblioteca **SQLAlchemy**.
2. Escrever os dados do arquivo CSV neste banco de dados local.
3. Realizar três atualizações no banco de dados:
  * Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.
  * Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.
  * Criar um novo registro de cliente seguindo as especificações abaixo:
    * ID_Cliente: 6850985
    * Idade: 33
    * Grau_escolaridade: Doutorado
    * Estado_civil: Solteiro
    * Tamanho_familia: 1
    * Categoria_de_renda: Empregado
    * Ocupacao: TI
    * Anos_empregado: 2
    * Rendimento_anual: 290000
    * Tem_carro: 0
    * Moradia: Casa/apartamento próprio

**Dica importante**: Para adicionar um(a) novo(a) cliente à tabela, utilize a cláusula **INSERT INTO** seguida do nome da tabela e depois especifique entre parênteses os nomes das colunas da tabela. Utilize a cláusula **VALUES** e, em seguida, passe entre parênteses os novos valores para esse novo registro. Certifique-se de que os valores estejam na ordem correta e no formato adequado para cada coluna.

In [ ]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text
import pandas as pd

In [ ]:
engine = create_engine('sqlite:///:memory:')
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
dados = pd.read_csv(url)
dados.to_sql('clientes', engine, index=False)

438463

In [ ]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio
438462,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio

In [ ]:
inspector_2 = inspect(engine)
print(inspector_2.get_table_names())

['clientes']

In [ ]:
query_2 = 'select * from clientes'
df_clientes = pd.read_sql(text(query_2), engine)
print(df_clientes.head(3))

   ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2
1     5008805     32   Ensino superior  União-estável                2
2     5008806     58      Ensino médio         Casado                2

  Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  Tem_carro  \
0          Empregado      Outro              12          427500.0          1
1          Empregado      Outro              12          427500.0          1
2          Empregado  Segurança               3          112500.0          1

                    Moradia
0       Apartamento alugado
1       Apartamento alugado
2  Casa/apartamento próprio

In [ ]:
query_2 = 'SELECT * FROM clientes WHERE ID_Cliente = 6840104'
df_cliente = pd.read_sql(text(query_2), engine)
print(df_cliente)

   ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
0     6840104     62      Ensino médio   Divorciado                1

  Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  Tem_carro  \
0        Pensionista    Outro               0          135000.0          0

                    Moradia
0  Casa/apartamento próprio

In [ ]:
  query_2 = 'UPDATE clientes SET Rendimento_anual = 300000 WHERE ID_Cliente = 6840104'
  with engine.connect() as conn:
    result = conn.execute(text(query_2))
    conn.commit()

In [ ]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
query_2 = ' DELETE FROM clientes WHERE ID_Cliente = 5008809'
with engine.connect() as conn:
  result = conn.execute(text(query_2))
  conn.commit()

In [ ]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
query = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado,\
Rendimento_anual, Tem_carro, Moradia) VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/apartamento próprio")'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

In [ ]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio
438462,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio